version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    command: python app.py
    restart: unless-stopped

  # Optional: Add Redis for session storage or caching
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped

  # Optional: Add PostgreSQL for persistent storage
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_USER: ticketrouter
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: tickets
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data: